### ISSUE TITLE
Image zoom bug

### ISSUE THREAD

**Issue by mscdex** [arnaudleyder/magneticmediajs#1]
To reproduce:

1. On the demo site, click "Image with zoom feature."
2. Hover the mouse over the image so that the magnification circle appears.
3. Scroll the scroll wheel up and down.

The magnification circle moves up and down with the page when using the scroll wheel and when it does, if you move the mouse around again, the position of the circle is relative to the mouse.

**Comment by arnaudleyder** [comment]
Hi Brian, 

Thanks for the feedback. I can confirm the issue. I will have a fix for that in 1.3.3. Hopefully I can push it soon. 

Thanks
Arnaud

**Comment by arnaudleyder** [comment]
Fix in commit fbac5e4. Will push to https://www.magneticmediajs.com demo site when 1.3.3 has deployed on jsDelivr.
