### ISSUE TITLE
Enhancement: Put a note about need of initialization of gallery inside of $(document).ready()

### ISSUE THREAD

**Issue by Grelek** [arnaudleyder/magneticmediajs#3]
As I am not primarily front-end / javascript dev I spent approximately about 1 hour looking for how to initialize this gallery. Then I found out I called the init method when the document wasn't loaded (I tried to initialize outside of `$(document).ready()`) and it threw (for non-js devs) weird errors.

I think for a lot of (dumb) people as me it would be nice and helpful if there is some visible note in the documentation about the need of initialization inside of `$(document).ready()` because sometimes non-javascript devs have to deal with these tasks too. :)

**Comment by arnaudleyder** [comment]
Hi, 

Thanks for using Magneticmediajs and sorry to hear you had to tweak your brain for the setup. The recommendation is to put all JavaScript files at the bottom of your page just before the closing body tag. As such the $(document).ready() is not required (ie the DOM is already loaded). This is mentioned in the documentation though I agree it could be clearer and put forward. I will update the docs in that direction. 

Have a nice day,
Arnaud

**Comment by Grelek** [comment]
That's nice. Thank you. :)
